function copyAndTranslateComponent(componentName, dx, dy, dz)
    % Translate component using direct VBA command execution
    
    
       
       
        % Build the complete VBA command as a single string
        sCommand = sprintf(['With Transform\n' ...
                           '     .Reset\n' ...
                           '     .Name "%s"\n' ...
                           '     .Vector "%s", "%s", "%s"\n' ...
                           '     .UsePickedPoints "False"\n' ...
                           '     .InvertPickedPoints "False"\n' ...
                           '     .MultipleObjects "True"\n' ...
                           '     .GroupObjects "False"\n' ...
                           '     .Repetitions "1"\n' ...
                           '     .MultipleSelection "False"\n' ...
                           '     .Destination ""\n' ...
                           '     .Material ""\n' ...
                           '     .AutoDestination "True"\n' ...
                           '     .Transform "Shape", "Translate"\n' ...
                           'End With'], ...
                          componentName, num2str(dx), num2str(dy), num2str(dz));
        
        % Execute the command using VBA method
        % invoke(mws,'VBA', sCommand);
        
        
        % Update view
        % mws.invoke('Rebuild');
        
   
    
end