function create_vias2(mws, params)
    % CREATE_VIAS Creates all via patterns for CST antenna design
    %
    % Inputs:
    %   mws - CST microwave studio object
    %   params - Structure containing all design parameters
    
    % Create horizontal vias
    create_horizontal1_vias(mws, params);
    create_horizontal2_vias(mws, params);
    create_vertical1_vias(mws, params);
    create_vertical2_vias(mws, params);

    % create_cavity_vias1(mws, params);
    % create_cavity_vias2(mws, params);
    % create_cavity_vias3(mws, params);
    % create_cavity_vias4(mws, params);
    % create_cavity_vias5(mws, params);
    % create_cavity_vias6(mws, params);
    

    % create_SW_vias1(mws, params);
    % create_SW_vias2(mws, params);
    % create_SW_vias3(mws, params);
    % % create_SW_vias3_(mws, params);
    % create_SW_vias4(mws, params);
    % create_SW_vias5(mws, params);
    % create_SW_vias6(mws, params);
    % create_SW_vias7(mws, params);
    % create_SW_vias8(mws, params);
    % create_SW_vias9(mws, params);

    % create_grounding_vias1(mws, params);
    % create_grounding_vias2(mws, params);

    % create_bridge_vias1(mws, params);
    % create_bridge_vias2(mws, params);
    % 
    % create_bridge_copper_vias1(mws, params);
    % create_bridge_copper_vias2(mws, params);
    % 
    % create_air_bridgevia1(mws, params);
    % create_air_bridgevia2(mws, params);
    % create_air_bridgevia3(mws, params);
    % create_air_bridgevia4(mws, params);
    % create_port_vias1(mws, params);
    % create_port_vias2(mws, params);
    % create_port_vias3(mws, params);
    % create_port_vias4(mws, params);
    
end

%% Helper functions for each via pattern
function create_horizontal1_vias(mws, params)
    names = {'VL1', 'VL2', 'VL3', 'VL4','VL5', 'VL6', 'VL7', 'VL8','VL9', 'VL10',...
        'VL11', 'VL12', 'VL13', 'VL14','VL15', 'VL16', 'VL17', 'VL18','VL19', 'VL20',...
        'VL21', 'VL22', 'VL23', 'VL24','VL25','VL26', 'VL27', 'VL28','VL29', 'VL30','VL31'};

    for i = 1:numel(names)
        create_single_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            ['-L/2+v2' repmat('+p', 1, i-1)], 'W/2-v3', params);
    end

end

function create_horizontal2_vias(mws, params)
    names = {'VL32', 'VL33', 'VL34','VL35', 'VL36', 'VL37', 'VL38','VL39', 'VL40',...
        'VL41', 'VL42', 'VL43', 'VL44','VL45','VL46', 'VL47', 'VL48', 'VL49','VL50',...
        'VL51', 'VL52', 'VL53', 'VL54','VL55','VL56', 'VL57', 'VL58', 'VL59','VL60','VL61','VL62'};
    for i = 1:numel(names)
        create_single_via(mws, names{i}, 'copper2', 'Copper (annealed)', ...
            ['-L/2+v2' repmat('+p', 1, i-1)], '-W/2+v3', params);   
    end
end

function create_vertical1_vias(mws, params)
    names = {'V1', 'V2','V3'};
    for i = 1:numel(names)
        create_single_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2', ['W/2-v3-p' repmat('-p', 1, i-1)], params);   
    end
end

function create_vertical2_vias(mws, params)
    names = {'V4', 'V5','V6'};
    for i = 1:numel(names)
        create_single_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            'L/2-v2', ['W/2-v3-p' repmat('-p', 1, i-1)], params);   
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function create_cavity_vias1(mws, params)
    names = {'Vca1'};
    for i = 1:numel(names)
        create_cavity_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2+8*p', 'W/2-v3-k1*p', params);   
    end
end

function create_cavity_vias2(mws, params)
    names = {'Vca2'};
    for i = 1:numel(names)
        create_cavity_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2+15*p', 'W/2-v3-k2*p', params);   
    end
end

function create_cavity_vias3(mws, params)
    names = {'Vca3'};
    for i = 1:numel(names)
        create_cavity_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2+22*p', 'W/2-v3-k1*p', params);   
    end
end

function create_cavity_vias4(mws, params)
    names = {'Vca4'};
    for i = 1:numel(names)
        create_cavity_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2+8*p', '-W/2+v3+k1*p', params);   
    end
end

function create_cavity_vias5(mws, params)
    names = {'Vca5'};
    for i = 1:numel(names)
        create_cavity_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2+22*p', '-W/2+v3+k1*p', params);   
    end
end

function create_cavity_vias6(mws, params)
    names = {'Vca6'};
    for i = 1:numel(names)
        create_cavity_via(mws, names{i}, 'copper3', 'Copper (annealed)', ...
            '-L/2+v2+15*p', '-W/2+v3+k2*p', params);   
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function create_SW_vias1(mws, params)
    names = {'SW1', 'SW2', 'SW3', 'SW4','SW5', 'SW6', 'SW7', 'SW8','SW9', 'SW10',...
        'SW11', 'SW12', 'SW13', 'SW14','SW15', 'SW16', 'SW17', 'SW18','SW19', 'SW20',...
        'SW21', 'SW22', 'SW23', 'SW24','SW25','SW26', 'SW27', 'SW28','SW29'};
        % ,'SW21_1',...'SW22_1', 'SW23_1', 'SW24_1','SW25_1','SW26_1', 'SW27_1', 'SW28_1','SW29_1'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            ['-L/2+v2+v4' repmat('+p1', 1, i-1)], 'W/2-v3-v4*v5', params);
    end
end

function create_SW_vias2(mws, params)
    names = {'SW30','SW31','SW32','SW33', 'SW34','SW35', 'SW36', 'SW37', 'SW38','SW39', 'SW40',...
        'SW41', 'SW42', 'SW43', 'SW44','SW45','SW46', 'SW47', 'SW48', 'SW49','SW50',...
        'SW51', 'SW52', 'SW53', 'SW54','SW55','SW56', 'SW57', 'SW58'};
        % 'SW50_1','SW51_1', 'SW52_1', 'SW53_1', 'SW54_1','SW55_1','SW56_1', 'SW57_1', 'SW58_1'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            ['-L/2+v2+v4' repmat('+p1', 1, i-1)], 'W/2-v3-2*v4*v5', params);
    end
end

function create_SW_vias3(mws, params)
    names = { 'SW59','SW60','SW61','SW62','SW63','SW64','SW65','SW66',...
        'SW67','SW68','SW69','SW70','SW71','SW72','SW73','SW74','SW75','SW76','SW77','SW78',...
        'SW79','SW80','SW81','SW82','SW83','SW84','SW85','SW86','SW87'};
        % 'SW79_1','SW80_1','SW81_1','SW82_1','SW83_1','SW84_1','SW85_1','SW86_1','SW87_1'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            ['-L/2+v2+v4' repmat('+p1', 1, i-1)], 'W/2-v3-3*v4*v5', params);
    end
end

% function create_SW_vias3_(mws, params)
%     names = { 'SW59_','SW60_','SW61_','SW62_','SW63_','SW64_','SW65_','SW66_',...
%               'SW67_','SW68_','SW69_','SW70_','SW71_','SW72_','SW73_','SW74_','SW75_','SW76_','SW77_','SW78_',...
%               'SW79_','SW80_','SW81_','SW82_','SW83_','SW84_','SW85_','SW86_','SW87_'...
%               'SW79_2','SW80_2','SW81_2','SW82_2','SW83_2','SW84_2','SW85_2','SW86_2','SW87_2'};
%     for i = 1:numel(names)
%         create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
%             ['-L/2+v2+v4' repmat('+p1', 1, i-1)], 'W/2-v3-4*v4*v5', params);
%     end
% end


function create_SW_vias4(mws, params)
    names = { 'SW88','SW89','SW90','SW91','SW92'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            '-L/2+v2+v4+3*P-k3', ['W/2-v3-4*v4' repmat('-p1', 1, i-1)], params);
    end
end

function create_SW_vias5(mws, params)
    names = { 'SW93','SW94','SW95','SW96'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            '-L/2+v2+v4+4*P-k3', ['W/2-v3-4*v4' repmat('-p1', 1, i-1)], params);
    end
end

function create_SW_vias6(mws, params)
    names = { 'SW97','SW98','SW99','SW100','SW101'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            '-L/2+v2+v4+5*P-k3', ['W/2-v3-4*v4' repmat('-p1', 1, i-1)], params);
    end
end

function create_SW_vias7(mws, params)
    names = { 'SW102','SW103','SW104','SW105','SW106'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            'L/2-v2-v4-5*P+k3', ['W/2-v3-4*v4' repmat('-p1', 1, i-1)], params);
    end
end

function create_SW_vias8(mws, params)
    names = { 'SW107','SW108','SW109','SW110'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            'L/2-v2-v4-4*P+k3', ['W/2-v3-4*v4' repmat('-p1', 1, i-1)], params);
    end
end

function create_SW_vias9(mws, params)
    names = { 'SW111','SW112','SW113','SW114','SW115'};
    for i = 1:numel(names)
        create_SW_via(mws, names{i}, 'copper1', 'Copper (annealed)', ...
            'L/2-v2-v4-3*P+k3', ['W/2-v3-4*v4' repmat('-p1', 1, i-1)], params);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function create_grounding_vias1(mws, params)
    names = {'Vgr1', 'Vgr2', 'Vgr3','Vgr4','Vgr5'};
    for i = 1:numel(names)
        create_single_via(mws, names{i}, 'copper2', 'Copper (annealed)', ...
            '-L/2+v2', ['-W/2+v3-3/2*p' repmat('-p', 1, i-1)], params);   
    end
end

function create_grounding_vias2(mws, params)
    names = {'Vgr7', 'Vgr8', 'Vgr9','Vgr10','Vgr11'};
    for i = 1:numel(names)
        create_single_via(mws, names{i}, 'copper2', 'Copper (annealed)', ...
            'L/2-v2', ['-W/2+v3-3/2*p' repmat('-p', 1, i-1)], params);   
    end
end


function create_bridge_vias1(mws, params)
    names = {'Vbr1'};
    for i = 1:numel(names)
        create_bridge_vias_1(mws, names{i}, 'Rogers', 'material1', ...
            'h1+h2+h+0.2','-W/2+c1-Y2-A1/2', params);   
    end
end

function create_bridge_vias2(mws, params)
    names = {'Vbr2'};
    for i = 1:numel(names)
        create_bridge_vias_2(mws, names{i}, 'Rogers', 'material1', ...
            'h1+h+h2+0.2','-W/2+c1-Y2-A1/2', params);   
    end
end


function create_bridge_copper_vias1(mws, params)
    names = {'Vbr3'};
    for i = 1:numel(names)
        create_bridge_copper_vias_1(mws, names{i}, 'copper2', 'Copper (annealed)', ...
            'h1+h+h2+0.2','-W/2+c1-Y2-A1/2', params);   
    end
end

function create_bridge_copper_vias2(mws, params)
    names = {'Vbr4'};
    for i = 1:numel(names)
        create_bridge_copper_vias_2(mws, names{i}, 'copper2', 'Copper (annealed)', ...
            'h1+h+h2+0.2','-W/2+c1-Y2-A1/2', params);   
    end
end

% function create_air_bridgevia1(mws, params)
%     names = {'AirV1','AirV1_1','AirV1_2','AirV1_3'};
%     for i = 1:numel(names)
%         create_AirbridgeVia(mws, names{i}, 'copper3', 'Copper (annealed)', ...
%             ['L/2-p_3+A1/2+cpw' repmat('-p', 1, i-1)], '-W/2+c1-Y1/2', params); 
%     end
% end
% 
% function create_air_bridgevia2(mws, params)
%     names = {'AirV2','AirV2_1','AirV2_2','AirV2_3'};
%     for i = 1:numel(names)
%         create_AirbridgeVia(mws, names{i}, 'copper3', 'Copper (annealed)', ...
%             ['-L/2+p_3-A1/2-cpw' repmat('+p', 1, i-1)], '-W/2+c1-Y1/2', params);   
%     end
% end
% 
% function create_air_bridgevia3(mws, params)
%     names = {'AirV3','AirV3_1','AirV3_2','AirV3_3'};
%     for i = 1:numel(names)
%         create_AirbridgeVia(mws, names{i}, 'copper3', 'Copper (annealed)', ...
%             ['L/2-p_3-w_3-cpw-A1/2' repmat('+p', 1, i-1)], '-W/2+c1-Y1/2', params);   
%     end
% end
% function create_air_bridgevia4(mws, params)
%     names = {'AirV4','AirV4_1','AirV4_2','AirV4_3'};
%     for i = 1:numel(names)
%         create_AirbridgeVia(mws, names{i}, 'copper3', 'Copper (annealed)', ...
%             ['-L/2+p_3+w_3+cpw+A1/2' repmat('-p', 1, i-1)], '-W/2+c1-Y1/2', params);   
%     end
% end
% 
% % % % % % % port vias
% function create_port_vias1(mws, params)
%     names = { 'port1','port2','port3','port4','port5'};
%     for i = 1:numel(names)
%         create_port_vias(mws, names{i}, 'copper1', 'Copper (annealed)', ...
%             'L/2-p_3+A3', ['-W/2+v3-P/2' repmat('-p', 1, i-1)], params);
%     end
% end
% 
% function create_port_vias2(mws, params)
%     names = { 'port6','port7','port8','port9','port10'};
%     for i = 1:numel(names)
%         create_port_vias(mws, names{i}, 'copper1', 'Copper (annealed)', ...
%             'L/2-p_3-w_3-A3', ['-W/2+v3-P/2' repmat('-p', 1, i-1)], params);
%     end
% end
% 
% function create_port_vias3(mws, params)
%     names = { 'port11','port12','port13','port14','port15'};
%     for i = 1:numel(names)
%         create_port_vias(mws, names{i}, 'copper1', 'Copper (annealed)', ...
%             '-L/2+p_3+w_3+A3', ['-W/2+v3-P/2' repmat('-p', 1, i-1)], params);
%     end
% end
% 
% function create_port_vias4(mws, params)
%     names = { 'port16','port17','port18','port19','port20'};
%     for i = 1:numel(names)
%         create_port_vias(mws, names{i}, 'copper1', 'Copper (annealed)', ...
%             '-L/2+p_3-A3', ['-W/2+v3-P/2' repmat('-p', 1, i-1)], params);
%     end
% end

function create_single_via(mws, name, component, material, x_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.0"\n' ...
                       '.Axis "z"\n' ...
                       '.Zrange "%g","%g"\n' ...
                       '.Xcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       params.v_d, 0, params.h+params.h1+params.h2, ...
                       x_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end

function create_SW_via(mws, name, component, material, x_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.0"\n' ...
                       '.Axis "z"\n' ...
                       '.Zrange "%g","%g"\n' ...
                       '.Xcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       params.v_d, 0, params.h+params.h1, ...
                       x_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end


function create_cavity_via(mws, name, component, material, x_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.0"\n' ...
                       '.Axis "z"\n' ...
                       '.Zrange "%g","%g"\n' ...
                       '.Xcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       params.v_d, params.h1, params.h+params.h1+params.h2, ...
                       x_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end



% % % % port fencing vias
% function create_port_vias(mws, name, component, material, x_center_expr, y_center_expr, params)
%     % CREATE_SINGLE_VIA Creates a single via in CST
%     sCommand = sprintf(['With Cylinder\n' ...
%                        '.Reset\n' ...
%                        '.Name "%s"\n' ...
%                        '.Component "%s"\n' ...
%                        '.Material "%s"\n' ...
%                        '.OuterRadius "%g/2"\n' ...
%                        '.InnerRadius "0.0"\n' ...
%                        '.Axis "z"\n' ...
%                        '.Zrange "%g","%g"\n' ...
%                        '.Xcenter "%s"\n' ...
%                        '.Ycenter "%s"\n' ...
%                        '.Segments "0"\n' ...
%                        '.Create\n' ...
%                        'End With'], ...
%                        name, component, material, ...
%                        params.v_d, 0, params.h+params.h1+params.h2, ...
%                        x_center_expr, y_center_expr);
% 
%     invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
% end


% function create_AirbridgeVia(mws, name, component, material, x_center_expr, y_center_expr, params)
%     % CREATE_SINGLE_VIA Creates a single via in CST
%     sCommand = sprintf(['With Cylinder\n' ...
%                        '.Reset\n' ...
%                        '.Name "%s"\n' ...
%                        '.Component "%s"\n' ...
%                        '.Material "%s"\n' ...
%                        '.OuterRadius "%g/2"\n' ...
%                        '.InnerRadius "0.0"\n' ...
%                        '.Axis "z"\n' ...
%                        '.Zrange "%g","%g"\n' ...
%                        '.Xcenter "%s"\n' ...
%                        '.Ycenter "%s"\n' ...
%                        '.Segments "0"\n' ...
%                        '.Create\n' ...
%                        'End With'], ...
%                        name, component, material, ...
%                        params.v_d/3, 0, params.h+params.h1+params.h2, ...
%                        x_center_expr, y_center_expr);
% 
%     invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
% end


function create_bridge_vias_1(mws, name, component, material, z_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.05"\n' ...
                       '.Axis "x"\n' ...
                       '.Xrange "%g","%g"\n' ...
                       '.Zcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       params.v_d/2, params.L/2-params.p_3-params.w_3-params.cpw,params.L/2-params.p_3+params.cpw, ...
                       z_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end


function create_bridge_vias_2(mws, name, component, material, z_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.05"\n' ...
                       '.Axis "x"\n' ...
                       '.Xrange "%g","%g"\n' ...
                       '.Zcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       params.v_d/2, -params.L/2+params.p_3+params.w_3+params.cpw,-params.L/2+params.p_3-params.cpw, ...
                       z_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end


function create_bridge_copper_vias_1(mws, name, component, material, z_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.0"\n' ...
                       '.Axis "x"\n' ...
                       '.Xrange "%g","%g"\n' ...
                       '.Zcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       0.1, params.L/2-params.p_3-params.w_3-params.A1-params.cpw,params.L/2-params.p_3+params.A1+params.cpw, ...
                       z_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end

function create_bridge_copper_vias_2(mws, name, component, material, z_center_expr, y_center_expr, params)
    % CREATE_SINGLE_VIA Creates a single via in CST
    sCommand = sprintf(['With Cylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.OuterRadius "%g/2"\n' ...
                       '.InnerRadius "0.0"\n' ...
                       '.Axis "x"\n' ...
                       '.Xrange "%g","%g"\n' ...
                       '.Zcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "0"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, ...
                       0.10, -params.L/2+params.p_3+params.w_3+params.A1+params.cpw,-params.L/2+params.p_3-params.A1-params.cpw, ...
                       z_center_expr, y_center_expr);

    invoke(mws, 'AddToHistory', ['define via:', component, ':', name], sCommand);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
