function create_Ecylinder(mws, name, component, material, xradius, yradius, axis, zrange_start, zrange_end, xcenter, ycenter, segments)
    % CREATE_CYLINDER Creates a cylinder in CST using the specified format
    % Inputs:
    %   mws           - CST application object
    %   name          - Name of the cylinder
    %   component     - Component name
    %   material      - Material name
    %   xradius       - X radius
    %   yradius       - Y radius
    %   axis          - Axis direction ('x', 'y', or 'z')
    %   zrange_start  - Z range start
    %   zrange_end    - Z range end
    %   xcenter       - X center coordinate
    %   ycenter       - Y center coordinate
    %   segments      - Number of segments
    
    sCommand = sprintf(['With ECylinder\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.Component "%s"\n' ...
                       '.Material "%s"\n' ...
                       '.Xradius "%s"\n' ...
                       '.Yradius "%s"\n' ...
                       '.Axis "%s"\n' ...
                       '.Zrange "%s", "%s"\n' ...
                       '.Xcenter "%s"\n' ...
                       '.Ycenter "%s"\n' ...
                       '.Segments "%s"\n' ...
                       '.Create\n' ...
                       'End With'], ...
                       name, component, material, xradius, yradius, axis, ...
                       zrange_start, zrange_end, xcenter, ycenter, segments);

    invoke(mws, 'AddToHistory', ['define ecylinder:', component, ':', name], sCommand);
end