function Cst4PortAdv(mws, port_data)
% CST4PORTADV Creates 4 waveguide ports with individual control
%   Cst4PortAdv(mws, port_data)
%
% Input:
%   mws       - CST application COM object
%   port_data - Structure array with these fields for each port:
%     .face_id      - Face ID (e.g., '1', '2')
%     .Yrange       - Y-dimension range (e.g., '"0", "W"')
%     .port_num     - Port number (1-4)
%     .orientation  - 'positive' or 'negative' (default: 'positive')
%     .ref_plane    - Reference plane distance (default: 0)
%     .layer        - Layer name (default: 'copper:top layer')

    % Default values
    default_orientation = 'positive';
    default_ref_plane = 0;
    default_layer = 'copper:top layer';

    for p = 1:2
        % Get current port data (with defaults)
        if p <= numel(port_data)
            pd = port_data(p);
            if ~isfield(pd, 'orientation'), pd.orientation = default_orientation; end
            if ~isfield(pd, 'ref_plane'), pd.ref_plane = default_ref_plane; end
            if ~isfield(pd, 'layer'), pd.layer = default_layer; end
        else
            error('Insufficient port_data entries');
        end

        % Pick face
        sCommand = sprintf('Pick.PickFaceFromId "%s", "%s"', pd.layer, pd.face_id);
        invoke(mws, 'AddToHistory', sprintf('pick face port%d', pd.port_num), sCommand);

        % Port definition
        sCommand = [...
            sprintf('\nWith Port')...
            sprintf('\n.Reset')...
            sprintf('\n.PortNumber %d', pd.port_num)...
            sprintf('\n.Label ""')...
            sprintf('\n.NumberOfModes 1')...
            sprintf('\n.AdjustPolarization "False"')...
            sprintf('\n.PolarizationAngle 0.0')...
            sprintf('\n.ReferencePlaneDistance %f', pd.ref_plane)...
            sprintf('\n.TextSize 50')...
            sprintf('\n.TextMaxLimit 0')...
            sprintf('\n.Coordinates "Picks"')...
            sprintf('\n.Orientation "%s"', pd.orientation)...
            sprintf('\n.PortOnBound "False"')...
            sprintf('\n.ClipPickedPortToBound "False"')...
            sprintf('\n.Xrange %s', pd.Xrange)...
            sprintf('\n.Yrange %s', pd.Yrange)...
            sprintf('\n.Zrange "0", "0"')...
            sprintf('\n.XrangeAdd %s', pd.XrangeAdd)...
            sprintf('\n.YrangeAdd %s', pd.YrangeAdd)...
            sprintf('\n.ZrangeAdd "2*h1+h2", "2.8"')...
            sprintf('\n.SingleEnded "False"')...
            sprintf('\n.Create')...
            sprintf('\nEnd With')];

        invoke(mws, 'AddToHistory', sprintf('define port%d', pd.port_num), sCommand);
    end
end