function setup_optimization(mws, opt_params)
    % SETUP_OPTIMIZATION Configures optimization parameters in CST
    %
    % Inputs:
    %   mws - CST microwave studio object
    %   opt_params - Structure containing optimization parameters
    
    %% Create Simulation Task
    sCommand = sprintf(['With SimulationTask\n' ...
                       '.Reset\n' ...
                       '.Name "%s"\n' ...
                       '.If Not .DoesExist Then\n' ...
                       '.Type "Optimization"\n' ...
                       '.Create\n' ...
                       '.Reset\n' ...
                       '.Type "S-Parameters"\n' ...
                       '.Name "%s"\n' ...
                       '.SetProperty "fmin", %g\n' ...
                       '.SetProperty "fmax", %g\n' ...
                       '.SetProperty "maximum frequency range", "%s"\n' ...
                       '.Create\n' ...
                       '.End If\n' ...
                       'End With'], ...
                       opt_params.task_name, ...
                       opt_params.task_path, ...
                       opt_params.fmin, ...
                       opt_params.fmax, ...
                       opt_params.max_freq_range);
    
    invoke(mws, 'AddToHistory', ['define optimization task: ' opt_params.task_name], sCommand);
    
    %% Configure Optimizer
    sCommand = sprintf(['With DSOptimizer\n' ...
                       '.SetSimulationType "%s"\n' ...
                       '.SetOptimizerType "%s"\n' ...
                       '.SetAlwaysStartFromCurrent "%s"\n' ...
                       '.InitParameterList\n' ...
                       '%s' ...  % Parameter configurations
                       '.DeleteAllGoals\n' ...
                       '%s' ...  % Goal configurations
                       '.Start\n' ...
                       'End With'], ...
                       opt_params.sim_type, ...
                       opt_params.optimizer_type, ...
                       opt_params.start_from_current, ...
                       get_parameter_commands(opt_params), ...
                       get_goal_commands(opt_params));
    
    invoke(mws, 'AddToHistory', 'configure optimizer', sCommand);
end

function param_commands = get_parameter_commands(opt_params)
    % Helper function to generate parameter configuration commands
    param_commands = '';
    for i = 1:size(opt_params.parameters, 1)
        param = opt_params.parameters(i,:);
        param_commands = [param_commands sprintf(['.SelectParameter "%s", "%s"\n' ...
                                                '.SetParameterInit "%g"\n' ...
                                                '.SetParameterMin "%g"\n' ...
                                                '.SetParameterMax "%g"\n'], ...
                                                param{1}, param{2}, param{3}, param{4}, param{5})];
    end
end

function goal_commands = get_goal_commands(opt_params)
    % Helper function to generate goal configuration commands
    goal_commands = sprintf(['.Dim gid As Integer\n' ...
                           'gid = .AddGoal "%s"\n' ...
                           '.SelectGoal(gid, "%s")\n' ...
                           '.SetGoal1DCResultName "%s"\n' ...
                           '.SetGoalScalarType "%s"\n' ...
                           '.SetGoalOperator "%s"\n' ...
                           '.SetGoalTarget "%g"\n' ...
                           '.SetGoalRangeType "%s"\n' ...
                           '.SetGoalRange "%s"\n'], ...
                           opt_params.goal.description, ...
                           opt_params.goal.select, ...
                           opt_params.goal.result_name, ...
                           opt_params.goal.scalar_type, ...
                           opt_params.goal.operator, ...
                           opt_params.goal.target, ...
                           opt_params.goal.range_type, ...
                           opt_params.goal.range);
end