function transformVias(mws, baseName, startNum, endNum, dx, dy, dz)
% TRANSFORMVIAS Transform multiple vias in CST
%   transformVias(mws, baseName, startNum, endNum, dx, dy, dz)
%
% Inputs:
%   mws - CST application COM object
%   baseName - Base name of vias (e.g., 'copper2:VL')
%   startNum - Starting via number
%   endNum - Ending via number
%   dx, dy, dz - Translation distances in x, y, z directions

    for n = startNum:endNum
        viaName = sprintf('%s%d', baseName, n);
        
        % Build the transform command
        cmd = sprintf(['With Transform\n' ...
                      '.Reset\n' ...
                      '.Name "%s"\n' ...
                      '.Vector "%f", "%f", "%f"\n' ...
                      '.UsePickedPoints "False"\n' ...
                      '.InvertPickedPoints "False"\n' ...
                      '.MultipleObjects "False"\n' ...
                      '.GroupObjects "False"\n' ...
                      '.Repetitions "1"\n' ...
                      '.MultipleSelection "False"\n' ...
                      '.AutoDestination "True"\n' ...
                      '.Transform "Shape", "Translate"\n' ...
                      'End With'], viaName, dx, dy, dz);
        
        % Execute command
        historyName = sprintf('transform %s', viaName);
        invoke(mws, 'AddToHistory', historyName, cmd);
    end
end